/*
Problem:
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.

Usage:
    $ gcc main.c -o sln
    $ ./sln
*/

#include <stdio.h>
#include <stdlib.h>

int fib       (int first, int second, int count, int *sequence);
int fib_rec   (int first, int second, int count, int *target);
int fib_print (int first, int second, int count);

int main (int argc, char* argv[])
{
    #define SEQ_LEN 35
    #define FIRST 1
    #define SECOND 2
    #define MAX 4000000

    int* sequence = malloc(SEQ_LEN * sizeof(int));
    int i         = 0;
    int sum       = 0;
    int value     = 0;

    fib(FIRST, SECOND, SEQ_LEN, sequence);

    for (i; i < SEQ_LEN; ++i) {
        value = sequence[i];
        if (value >= MAX)
            break;
        else if (value % 2 == 0) {
            sum += value;
        }
    }

    printf("%d\n", sum);

    free(sequence);
    return 0;
}


int fib(int first, int second, int count, int *sequence)
{
    sequence[0] = first;
    sequence[1] = second;
    
    return fib_rec(first, second, count - 2, sequence + 2);
}

int fib_rec(int first, int second, int count, int *target)
{
    if (count <= 0)
        return 0;

    *target = first + second;
    return fib_rec(second, *target, count - 1, target + 1);
}
